//! Concrete canonical circuit and witness types for the PSO protocol.
//!
//! The generic core (`pso-protocol`) defines only the seams — the
//! [`Circuit`](pso_protocol::protocol::zk::Circuit),
//! [`ProofGenerator`](pso_protocol::protocol::zk::ProofGenerator), and
//! [`ProofVerifier`](pso_protocol::protocol::zk::ProofVerifier) traits plus
//! the `Suite` formulas. This crate supplies the *concrete* statements built
//! on top of them, generated from the vendored noir circuits.
//!
//! The noir circuits fix the proving field to BN254, so the witness types are
//! `ark_bn254::Fr`-based. Rather than hardcode `PsoV1`, the circuit layer is
//! generic over [`CircuitSuite`] — any suite on the BN254/Grumpkin cycle that
//! signs with the in-circuit 64-byte Grumpkin Schnorr. `PsoV1` satisfies it;
//! a future same-cycle `PsoV2` would reuse the same circuits.
//!
//! The [`noir`] module is **build-generated** at compile time from the
//! vendored noir circuits in `noir/*.nr` via `nargo`. Per circuit it derives
//! the Rust `Witness` / `PublicInputs` types, a marker type with a generic
//! [`Circuit<S>`](pso_protocol::protocol::zk::Circuit) impl + a (suite-
//! independent) [`CircuitId`] identity impl, and the canonical descriptor
//! constants (`LABEL` / `VERSION` / `CIRCUIT_HASH` / `BYTECODE_B64` /
//! `VK_BYTES` / `VK_HASH`).
//!
//! The `.nr` circuits remain the source of truth.

pub mod aggregation;
pub mod full;
pub mod ownership;

/// The circuit seams live in the core (`pso-protocol`), so a noir backend can be
/// generic over circuits without depending on this crate. Re-exported here for
/// convenience — `pso_zk_canonical::{CircuitSuite, CircuitId}` and the
/// build-generated `crate::{…}` impls keep resolving.
pub use pso_protocol::protocol::zk::{CircuitId, CircuitSuite};

/// Depth of the perpetual TributeDraft commitment tree — the chain's
/// `CommitmentWindowBase.TREE_DEPTH` and the `full_proof` circuit's Merkle path
/// length. The generic [`pso_protocol::protocol::imt::Imt`] is depth-agnostic;
/// this pins the canonical depth the full-proof circuit is built for.
pub const INCLUSION_DEPTH: usize = 32;

/// Lifecycle status of a registered circuit version (see `circuits/manifest.toml`).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CircuitStatus {
    /// Accepts new proofs.
    Active,
    /// Still verifies in-flight proofs; no new adoption. Keeps its VK; the
    /// freeze step drops its bytecode (a proving artifact).
    Deprecated,
    /// Obsolete: no longer verifies (normal sunset or emergency kill-switch).
    /// The freeze step drops its VK too, and it is absent from
    /// [`CIRCUIT_REGISTRY`](noir::CIRCUIT_REGISTRY) — the manifest keeps the
    /// record (`circuit_hash`).
    Revoked,
}

/// One frozen, released circuit version in the in-code registry
/// ([`noir::CIRCUIT_REGISTRY`]). Append-only: new versions are added and old
/// ones kept until revoked, so a verifier can accept old + new concurrently.
///
/// This is the **verification** view — it carries only the VK, since
/// verification needs only the VK (+ public inputs + proof). The ACIR bytecode
/// is a *proving* artifact and is kept only for the **active** version, on its
/// `noir::<module>::BYTECODE_B64` const; old versions drop their bytecode (a
/// retired prover ships its own).
#[derive(Clone, Copy, Debug)]
pub struct RegistryEntry {
    /// Canonical dotted label (the logical statement), e.g. `pso.ownership`.
    pub label: &'static str,
    /// Semver version of this artifact.
    pub version: &'static str,
    /// Lifecycle status.
    pub status: CircuitStatus,
    /// Proof system these bytes verify under (the bb pin / verifier routing key).
    pub proof_system: &'static str,
    /// `keccak256(acir bytecode)` — the binary identity (preserved in the
    /// manifest after the bytecode itself is dropped).
    pub circuit_hash: [u8; 32],
    /// `keccak256(vk_bytes)`.
    pub vk_hash: [u8; 32],
    /// UltraHonkKeccak verification key — all that verification needs.
    pub vk_bytes: &'static [u8],
}

/// Rust types generated at build time from the **frozen** circuit artifacts
/// listed in `circuits/manifest.toml` (witness + public-input shapes + canonical
/// identity for the latest active version of each circuit, plus the full
/// append-only [`CIRCUIT_REGISTRY`](noir::CIRCUIT_REGISTRY) over every version).
#[allow(dead_code)]
#[allow(clippy::all)] // machine-generated by build.rs from the noir ABIs; not hand-linted
pub mod noir {
    include!(concat!(env!("OUT_DIR"), "/noir_generated.rs"));
}
