//! Noir/Barretenberg circuit integration for ZK proof generation and verification.
//!
//! Provides `NoirFullProofCircuit` and `NoirOwnershipCircuit` implementations
//! of the `ZKCircuit` trait, along with proof types, circuit configuration,
//! and bytecode loading utilities.

pub mod circuit_traits;
pub mod schnorr_grumpkin;
pub mod testing;
pub use circuit_traits::{Proof, ZKCircuit, ZKCircuitVersion};

use std::fmt::{Debug, Formatter};

use anyhow::Error;
use noir_rs::acir::native_types::WitnessMap;
use noir_rs::barretenberg::prove::{prove_ultra_honk, prove_ultra_honk_keccak};
use noir_rs::barretenberg::srs::setup_srs_from_bytecode;
use noir_rs::barretenberg::verify::{
    get_ultra_honk_keccak_verification_key, get_ultra_honk_verification_key, verify_ultra_honk,
    verify_ultra_honk_keccak,
};
use noir_rs::witness::from_vec_to_witness_map;
use noir_rs::{AcirField, FieldElement};

use pso_protocol::witness::{FullProofWitness, OwnershipWitness};

/// Compiled Noir circuit bytecode and its content hash.
pub struct CircuitBytecode {
    /// Base64-encoded ACIR bytecode produced by `nargo compile`.
    pub bytecode: String,
    /// Hash of the circuit for version tracking.
    pub hash: String,
}

impl Debug for CircuitBytecode {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        f.write_str(&format!("Circuit {{ hash: {} }}", self.hash))
    }
}

/// Proving scheme selector for Noir/Barretenberg.
#[derive(Debug)]
pub enum ZKMode {
    /// Standard UltraHonk proving scheme.
    UltraHonk,
    /// UltraHonk with Keccak transcript (EVM-verifiable).
    UltraHonkKeccak,
}

/// Configuration for setting up a Noir circuit.
#[derive(Debug)]
pub struct NoirCircuitConfig {
    /// Compiled circuit bytecode.
    pub circuit: CircuitBytecode,
    /// Semantic version string for the circuit.
    pub version: &'static str,
    /// Use low-memory mode for large circuits.
    pub low_memory: bool,
    /// Proving scheme to use.
    pub scheme: ZKMode,
}

/// A proof generated by the Noir/Barretenberg backend.
#[derive(Ord, PartialOrd, Eq, PartialEq)]
pub struct NoirProof {
    /// Raw proof bytes (without public inputs).
    pub proof: Vec<u8>,
    /// Public input field elements as byte vectors.
    pub public_inputs: Vec<Vec<u8>>,
}

impl Debug for NoirProof {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        f.write_str(&format!(
            "NoirProof{{ proof: {}, public_inputs: {}, proof_bytes: {:0X?} }}",
            self.proof.len(),
            self.public_inputs.len(),
            self.proof
        ))
    }
}

impl Proof for NoirProof {
    fn proof(&self) -> String {
        bs58::encode(&self.proof).into_string()
    }

    fn public_inputs(&self) -> Vec<String> {
        let mut public_inputs = Vec::new();
        for input in &self.public_inputs {
            public_inputs.push(bs58::encode(input).into_string());
        }

        public_inputs
    }
}

/// Splits a proof containing a 4-byte public input count prefix into public inputs and proof bytes.
///
/// The proof format used by zkpassport/noir_rs is:
/// ```text
/// [num_public_inputs (4 bytes BE)] [public_input_0: 32B] [public_input_1: 32B] ... [proof_bytes...]
/// ```
///
/// # Arguments
/// * `proof` - The combined proof with count prefix
///
/// # Returns
/// A tuple of (public_inputs, proof_bytes) where:
/// * `public_inputs` - Vector of public input byte vectors (each 32 bytes)
/// * `proof_bytes` - The remaining proof bytes after removing count and inputs
///
/// # Errors
/// Returns an error if the proof is malformed (too short or incomplete public inputs).
pub fn split_proof(proof: &[u8]) -> Result<(Vec<Vec<u8>>, Vec<u8>), String> {
    if proof.len() < 4 {
        return Err("proof too short: missing public input count prefix".to_string());
    }

    let num_public_inputs = u32::from_be_bytes([proof[0], proof[1], proof[2], proof[3]]) as usize;
    let bytes_per_input = 32;
    let public_inputs_size = num_public_inputs * bytes_per_input;

    if proof.len() < 4 + public_inputs_size {
        return Err(format!(
            "invalid proof format: expected {} public input bytes, but only {} bytes available after count prefix",
            public_inputs_size,
            proof.len() - 4
        ));
    }

    let public_inputs_bytes = &proof[4..4 + public_inputs_size];
    let proof_bytes = &proof[4 + public_inputs_size..];

    let public_inputs = (0..num_public_inputs)
        .map(|i| public_inputs_bytes[i * 32..(i + 1) * 32].to_vec())
        .collect();

    Ok((public_inputs, proof_bytes.to_vec()))
}

/// Recombines public inputs and proof bytes into a single proof with 4-byte count prefix.
///
/// This is the inverse of `split_proof()` and is used for proof verification.
///
/// # Arguments
/// * `proof` - The raw proof bytes (without public inputs)
/// * `public_inputs` - The public input byte vectors (each 32 bytes)
///
/// # Returns
/// A combined proof with the format: [count: 4B BE][inputs...][proof...]
fn combine_proof(proof: Vec<u8>, public_inputs: Vec<Vec<u8>>) -> Vec<u8> {
    let num_public_inputs = public_inputs.len() as u32;
    let mut combined = Vec::new();
    combined.extend_from_slice(&num_public_inputs.to_be_bytes());

    for input in public_inputs {
        combined.extend_from_slice(&input);
    }

    combined.extend_from_slice(&proof);
    combined
}

impl NoirProof {
    fn to_noir_proof(&self) -> Vec<u8> {
        combine_proof(self.proof.clone(), self.public_inputs.clone())
    }

    /// Public accessor for the combined Honk proof bytes
    /// (`[num_inputs:4B BE][public_inputs:32B*K][proof]`). This is the
    /// exact byte layout consumed by the on-chain `zk_verify`
    /// precompile and emitted to wallets as the `aggregationProof`
    /// calldata.
    pub fn to_combined(&self) -> Vec<u8> {
        self.to_noir_proof()
    }
}

/// Noir circuit for full proofs (ownership + Merkle inclusion).
pub struct NoirFullProofCircuit {
    config: NoirCircuitConfig,
    _srs: u32,
    verification_key: Vec<u8>,
}

impl ZKCircuit<NoirCircuitConfig, NoirProof> for NoirFullProofCircuit {
    type Witness = FullProofWitness;

    fn setup(c: NoirCircuitConfig) -> anyhow::Result<Self> {
        let bytecode = &c.circuit.bytecode;
        let srs = setup_srs_from_bytecode(bytecode, None, false).map_err(Error::msg)?;
        let vk = match c.scheme {
            ZKMode::UltraHonk => get_ultra_honk_verification_key(bytecode, c.low_memory, None),
            ZKMode::UltraHonkKeccak => {
                get_ultra_honk_keccak_verification_key(bytecode, false, c.low_memory, None)
            }
        }
        .map_err(Error::msg)?;

        Ok(NoirFullProofCircuit {
            config: c,
            _srs: srs,
            verification_key: vk,
        })
    }

    fn version(&self) -> ZKCircuitVersion {
        ZKCircuitVersion {
            circuit_hash: self.config.circuit.hash.to_string(),
            circuit_version: self.config.version.to_string(),
            circuit_type: "noir".to_string(),
        }
    }

    fn prove(&self, witness: FullProofWitness) -> anyhow::Result<NoirProof> {
        let circuit = &self.config.circuit;
        let bytecode = &circuit.bytecode;
        let witness_map = NoirFullProofCircuit::create_witness_map(&witness).map_err(Error::msg)?;
        let proof = match self.config.scheme {
            ZKMode::UltraHonk => prove_ultra_honk(
                bytecode,
                witness_map,
                self.verification_key.clone(),
                self.config.low_memory,
                None,
            ),
            ZKMode::UltraHonkKeccak => prove_ultra_honk_keccak(
                bytecode,
                witness_map,
                self.verification_key.clone(),
                false,
                self.config.low_memory,
                None,
            ),
        }
        .map_err(|error| Error::msg(error.to_string()))?;

        let (public_inputs, proof_bytes) = split_proof(&proof).map_err(Error::msg)?;

        Ok(NoirProof {
            proof: proof_bytes,
            public_inputs,
        })
    }

    fn verify(&self, proof: NoirProof) -> Result<bool, Error> {
        let combined_proof = proof.to_noir_proof();

        match self.config.scheme {
            ZKMode::UltraHonk => verify_ultra_honk(combined_proof, self.verification_key.clone()),
            ZKMode::UltraHonkKeccak => {
                verify_ultra_honk_keccak(combined_proof, self.verification_key.clone(), false)
            }
        }
        .map_err(Error::msg)
    }
}

// Max depth of SMT, one block may contain 2^8 tributes
// so network can handle about 1M tributes per second
pub use pso_protocol::merkle::SPARSE_MERKLE_PATH_DEPTH;

impl NoirFullProofCircuit {
    fn create_witness_map(witness: &FullProofWitness) -> Result<WitnessMap<FieldElement>, Error> {
        // Circuit main() signature (must match exactly):
        //     pk: EmbeddedCurvePoint,
        //     signature: [u8; 64],
        //     nonce: Field,
        //     merkle_path_siblings: [Field; 8],
        //     merkle_path_indices: [u8; 8],
        //     owner: pub Field,
        //     nft_hash: pub Field,
        //     expected_merkle_root: pub Field,

        use pso_protocol::merkle::MerklePathElementIndex;

        let mut witness_vec = Vec::new();

        // pk.x as Field (Grumpkin coord, LE-decoded from 32 bytes)
        witness_vec.push(FieldElement::from_le_bytes_reduce(
            &witness.private_inputs.ownership.public_key_x,
        ));
        // pk.y as Field
        witness_vec.push(FieldElement::from_le_bytes_reduce(
            &witness.private_inputs.ownership.public_key_y,
        ));

        // signature as [u8; 64] -- Schnorr/Grumpkin (s || e)
        let signature = witness
            .public_inputs
            .ownership
            .signature
            .iter()
            .map(|byte| FieldElement::from(*byte as u32));
        witness_vec.extend(signature);

        // nonce as Field
        witness_vec.push(FieldElement::from_le_bytes_reduce(
            &witness.private_inputs.ownership.nonce,
        ));

        // merkle_path_siblings as [Field; 8] and merkle_path_indices as [u8; 8]
        {
            let diff = SPARSE_MERKLE_PATH_DEPTH - witness.private_inputs.merkle_path.len();

            // Siblings as Field values
            let mut merkle_path_siblings: Vec<FieldElement> = witness
                .private_inputs
                .merkle_path
                .iter()
                .map(|item| FieldElement::from_le_bytes_reduce(&item.node_hash))
                .collect();
            merkle_path_siblings.extend(vec![FieldElement::zero(); diff]);
            witness_vec.extend(merkle_path_siblings);

            // Indices mapped to Noir convention: Right->1 (current is left), Left->0 (sibling is left)
            let mut merkle_path_indices: Vec<FieldElement> = witness
                .private_inputs
                .merkle_path
                .iter()
                .map(|item| match item.index {
                    MerklePathElementIndex::Right => FieldElement::from(1u32),
                    MerklePathElementIndex::Left => FieldElement::zero(),
                    MerklePathElementIndex::Skip => FieldElement::zero(),
                })
                .collect();
            merkle_path_indices.extend(vec![FieldElement::zero(); diff]);
            witness_vec.extend(merkle_path_indices);
        }

        // expected_ownership as pub Field
        witness_vec.push(FieldElement::from_le_bytes_reduce(
            &witness.public_inputs.ownership.ownership,
        ));

        // nft_hash as pub Field — lives inside ownership now.
        witness_vec.push(FieldElement::from_le_bytes_reduce(
            &witness.public_inputs.ownership.nft_hash,
        ));

        // expected_merkle_root as pub Field
        witness_vec.push(FieldElement::from_le_bytes_reduce(
            &witness.public_inputs.merkle_root,
        ));

        from_vec_to_witness_map(witness_vec).map_err(Error::msg)
    }
}

// -- Ownership-only circuit --

/// Noir circuit for ownership-only proofs.
///
/// Proves knowledge of the private key corresponding to an ownership hash,
/// without requiring Merkle inclusion.
pub struct NoirOwnershipCircuit {
    config: NoirCircuitConfig,
    _srs: u32,
    verification_key: Vec<u8>,
}

impl ZKCircuit<NoirCircuitConfig, NoirProof> for NoirOwnershipCircuit {
    type Witness = OwnershipWitness;

    fn setup(c: NoirCircuitConfig) -> anyhow::Result<Self> {
        let bytecode = &c.circuit.bytecode;
        let srs = setup_srs_from_bytecode(bytecode, None, false).map_err(Error::msg)?;
        let vk = match c.scheme {
            ZKMode::UltraHonk => get_ultra_honk_verification_key(bytecode, c.low_memory, None),
            ZKMode::UltraHonkKeccak => {
                get_ultra_honk_keccak_verification_key(bytecode, false, c.low_memory, None)
            }
        }
        .map_err(Error::msg)?;

        Ok(NoirOwnershipCircuit {
            config: c,
            _srs: srs,
            verification_key: vk,
        })
    }

    fn version(&self) -> ZKCircuitVersion {
        ZKCircuitVersion {
            circuit_hash: self.config.circuit.hash.to_string(),
            circuit_version: self.config.version.to_string(),
            circuit_type: "noir-ownership".to_string(),
        }
    }

    fn prove(&self, witness: OwnershipWitness) -> anyhow::Result<NoirProof> {
        let circuit = &self.config.circuit;
        let bytecode = &circuit.bytecode;
        let witness_map =
            NoirOwnershipCircuit::create_ownership_witness_map(&witness).map_err(Error::msg)?;
        let proof = match self.config.scheme {
            ZKMode::UltraHonk => prove_ultra_honk(
                bytecode,
                witness_map,
                self.verification_key.clone(),
                self.config.low_memory,
                None,
            ),
            ZKMode::UltraHonkKeccak => prove_ultra_honk_keccak(
                bytecode,
                witness_map,
                self.verification_key.clone(),
                false,
                self.config.low_memory,
                None,
            ),
        }
        .map_err(|error| Error::msg(error.to_string()))?;

        let (public_inputs, proof_bytes) = split_proof(&proof).map_err(Error::msg)?;

        Ok(NoirProof {
            proof: proof_bytes,
            public_inputs,
        })
    }

    fn verify(&self, proof: NoirProof) -> Result<bool, Error> {
        let combined_proof = proof.to_noir_proof();

        match self.config.scheme {
            ZKMode::UltraHonk => verify_ultra_honk(combined_proof, self.verification_key.clone()),
            ZKMode::UltraHonkKeccak => {
                verify_ultra_honk_keccak(combined_proof, self.verification_key.clone(), false)
            }
        }
        .map_err(Error::msg)
    }
}

impl NoirOwnershipCircuit {
    /// Create a witness map for the Schnorr/Grumpkin ownership-only
    /// circuit.
    ///
    /// Circuit `main()` parameter order (must match
    /// `pso-ownership-circuit/src/main.nr`):
    ///
    /// ```text
    /// pk          : EmbeddedCurvePoint    // private — 2 Fields (pk.x, pk.y)
    /// signature   : [u8; 64]              // private — 64 bytes (Schnorr s||e)
    /// nonce       : Field                 // private
    /// owner       : pub Field
    /// nft_hash    : pub Field
    /// ```
    ///
    /// `public_key_x` / `public_key_y` in `OwnershipPrivateInputs` are
    /// 32-byte LE encodings of Grumpkin Fr coordinates (was: SEC1
    /// bytes for secp256k1).
    fn create_ownership_witness_map(
        witness: &OwnershipWitness,
    ) -> Result<WitnessMap<FieldElement>, Error> {
        let mut witness_vec = Vec::new();

        // pk.x as one Field (Grumpkin coord, LE-decoded from 32 bytes)
        witness_vec.push(FieldElement::from_le_bytes_reduce(
            &witness.private_inputs.public_key_x,
        ));
        // pk.y as one Field
        witness_vec.push(FieldElement::from_le_bytes_reduce(
            &witness.private_inputs.public_key_y,
        ));
        // signature as [u8; 64] — Schnorr/Grumpkin (s || e). The
        // `noir-lang/schnorr` crate expects this layout exactly.
        for &byte in witness.public_inputs.signature.iter() {
            witness_vec.push(FieldElement::from(byte as u32));
        }
        // nonce as Field
        witness_vec.push(FieldElement::from_le_bytes_reduce(
            &witness.private_inputs.nonce,
        ));

        // owner as pub Field
        witness_vec.push(FieldElement::from_le_bytes_reduce(
            &witness.public_inputs.ownership,
        ));
        // nft_hash as pub Field
        witness_vec.push(FieldElement::from_le_bytes_reduce(
            &witness.public_inputs.nft_hash,
        ));

        from_vec_to_witness_map(witness_vec).map_err(Error::msg)
    }
}

// -- Flat aggregation circuit wrapper --------------------------------- //
//
// `NoirFlatAggregationCircuit` is intentionally NOT defined here. The
// flat tier circuits (`pso-flat-aggregation-circuit-n*`) have a
// witness shape parameterised by `N` (N copies of `(pk, signature,
// nonce)` plus `2*N` public inputs), which is naturally expressed by
// a generic over `const N: u32` on the consumer side. The wallet
// integration in `pso-integration::pso-integrations-shared::witness`
// owns the witness builders and the noir_rs prove call site so the
// circuit core stays minimal -- this crate only owns the standalone
// ownership + full-proof wrappers above.

/// Derive the canonical UltraHonkKeccak verification key for a
/// compiled Noir circuit, via the noir_rs FFI.
///
/// **This is the function `xtask regenerate-canonical` calls** to mint
/// the `vk_bytes` field of every `pso_zk_canonical::CircuitDescriptor`.
/// Must match the verifier path bit-for-bit: at runtime, the on-chain
/// `zk_verify` precompile passes the same canonical bytes to
/// `verify_ultra_honk_keccak`, and wallets generate proofs via
/// `prove_ultra_honk_keccak`. All three calls go through the same FFI
/// against the same `settings_ultra_honk_keccak`, so the artifacts
/// are guaranteed compatible.
///
/// Historical note: an earlier version of the xtask shelled out to
/// `bb write_vk --scheme ultra_honk --oracle_hash keccak` instead. That
/// produced different VK bytes than this FFI path, with the result that
/// no real (prover-generated) proof would verify against the committed
/// canonical VKs. The CLI / FFI difference is at the encoding layer
/// (different settings defaults — `optimized_solidity_verifier`,
/// `ipa_accumulation`, internal serialization). Going through the FFI
/// removes the divergence and keeps the design self-consistent.
pub fn derive_canonical_keccak_vk(bytecode: &str) -> anyhow::Result<Vec<u8>> {
    // Provision a generous fixed BN254 SRS that covers all canonical
    // tiers. `setup_srs_from_bytecode`'s subgroup-size heuristic
    // undercounts for the larger flat-aggregation circuits (N=8+),
    // causing barretenberg to abort with `prover trying to get too
    // many points in MemBn254CrsFactory`. 2^21 = 2,097,152 points
    // covers our largest circuit (N=64 acir ~5.5 MB) with headroom
    // and the SRS download is cached locally after the first run.
    use noir_rs::barretenberg::srs::setup_srs;
    const SRS_POINTS: u32 = 1 << 21;
    let _ = setup_srs(SRS_POINTS, None).map_err(Error::msg)?;
    let vk =
        get_ultra_honk_keccak_verification_key(bytecode, false, false, None).map_err(Error::msg)?;
    Ok(vk)
}

pub mod circuit_loader {
    use super::*;

    use anyhow::anyhow;
    use std::path::Path;

    /// Load the compiled Noir circuit bytecode from a JSON file
    ///
    /// The bytecode is generated by running `nargo compile` in the circuits directory.
    /// The output is typically found at `circuits/target/<circuit_name>.json`.
    pub fn load_circuit<P: AsRef<Path>>(path: P) -> anyhow::Result<CircuitBytecode> {
        let content = std::fs::read_to_string(path.as_ref())?;

        load_circuit_from_str(&content)
    }

    /// Load circuit bytecode from a string (useful for embedded bytecode)
    pub fn load_circuit_from_str(content: &str) -> anyhow::Result<CircuitBytecode> {
        // Parse JSON and extract the bytecode field
        let json: serde_json::Value =
            serde_json::from_str(content).map_err(|e| anyhow!("Invalid JSON: {}", e))?;

        // The bytecode is in the "bytecode" field of the compiled JSON
        let bytecode = json
            .get("bytecode")
            .and_then(|v| v.as_str())
            .ok_or_else(|| anyhow!("Missing 'bytecode' field in circuit JSON"))?
            .trim()
            .to_string();

        let hash = json
            .get("hash")
            .and_then(|v| v.as_str())
            .ok_or_else(|| anyhow!("Missing 'hash' field in circuit JSON"))?
            .trim()
            .to_string();

        Ok(CircuitBytecode { bytecode, hash })
    }
}

#[cfg(test)]
mod tests {
    use crate::{
        circuit_loader, split_proof, NoirCircuitConfig, NoirFullProofCircuit, NoirOwnershipCircuit,
        ZKMode, SPARSE_MERKLE_PATH_DEPTH,
    };
    use ark_bn254::Fr;
    use ark_ff::UniformRand;
    use noir_rs::{AcirField, FieldElement};
    use rand::rngs::OsRng;

    use crate::{testing, ZKCircuit};
    use pso_protocol::merkle::{MerklePathElement, MerklePathElementIndex};
    use pso_protocol::witness::{FullProofWitness, HashableNFT, OwnableNFT};

    // -- Test-local NFT that does not depend on any domain crate --

    /// Minimal NFT implementation for circuit testing.
    /// Uses random `nft_hash` since the circuit does not verify the hash formula.
    struct TestNFT {
        ownership: Fr,
        nft_hash: Fr,
    }

    impl OwnableNFT for TestNFT {
        fn ownership(&self) -> Fr {
            self.ownership
        }
    }

    impl HashableNFT for TestNFT {
        fn hash(&self) -> Result<Fr, pso_protocol::ProtocolError> {
            Ok(self.nft_hash)
        }
    }

    /// Create a TestNFT with random crypto data.
    fn make_test_nft() -> (TestNFT, testing::GrumpkinKey, Fr, Vec<MerklePathElement>) {
        let key = testing::random_grumpkin_key().expect("random grumpkin key");
        let nonce = Fr::rand(&mut OsRng);

        let ownership = testing::ownership_from_grumpkin_key(&key, nonce).unwrap();
        let nft_hash = Fr::rand(&mut OsRng);

        let merkle_depth = 6;
        let mut merkle_path = Vec::with_capacity(merkle_depth);
        for _ in 0..merkle_depth {
            let random_hash = Fr::rand(&mut OsRng);
            let array = testing::fr_to_le32(&random_hash);

            merkle_path.push(MerklePathElement {
                node_hash: array,
                index: if rand::random() {
                    MerklePathElementIndex::Left
                } else {
                    MerklePathElementIndex::Right
                },
            });
        }

        let nft = TestNFT {
            ownership,
            nft_hash,
        };
        (nft, key, nonce, merkle_path)
    }

    // -- Helper --

    /// Dumps witness data as a complete Noir `#[test]` function that calls `main()`.
    /// The output can be copy-pasted into `main.nr` to debug circuit failures via `nargo test`.
    fn dump_witness_for_noir_tests(witness: &FullProofWitness) {
        let nonce = FieldElement::from_le_bytes_reduce(&witness.private_inputs.ownership.nonce);
        let expected_ownership =
            FieldElement::from_le_bytes_reduce(&witness.public_inputs.ownership.ownership);
        let nft_hash =
            FieldElement::from_le_bytes_reduce(&witness.public_inputs.ownership.nft_hash);
        let expected_merkle_root =
            FieldElement::from_le_bytes_reduce(&witness.public_inputs.merkle_root);

        fn fmt_bytes(bytes: &[u8]) -> String {
            let items: Vec<String> = bytes.iter().map(|b| format!("{:03}", b)).collect();
            format!("[{}]", items.join(", "))
        }

        let mut sibling_strs: Vec<String> = witness
            .private_inputs
            .merkle_path
            .iter()
            .map(|item| {
                format!(
                    "0x{}",
                    FieldElement::from_le_bytes_reduce(&item.node_hash).to_hex()
                )
            })
            .collect();
        while sibling_strs.len() < SPARSE_MERKLE_PATH_DEPTH {
            sibling_strs.push("0".to_string());
        }

        let mut index_strs: Vec<String> = witness
            .private_inputs
            .merkle_path
            .iter()
            .map(|item| match item.index {
                MerklePathElementIndex::Right => "1".to_string(),
                MerklePathElementIndex::Left => "0".to_string(),
                MerklePathElementIndex::Skip => "0".to_string(),
            })
            .collect();
        while index_strs.len() < SPARSE_MERKLE_PATH_DEPTH {
            index_strs.push("0".to_string());
        }

        println!("// --- Generated Noir test (copy-paste into main.nr) ---");
        println!("#[test]");
        println!("fn test_main_integration() {{");
        println!("    let nonce: Field = 0x{};", nonce.to_hex());
        println!(
            "    let pk_x_bytes: [u8; 32] = {};",
            fmt_bytes(&witness.private_inputs.ownership.public_key_x)
        );
        println!(
            "    let pk_y_bytes: [u8; 32] = {};",
            fmt_bytes(&witness.private_inputs.ownership.public_key_y)
        );
        println!(
            "    let signature: [u8; 64] = {};",
            fmt_bytes(&witness.public_inputs.ownership.signature)
        );
        println!(
            "    let merkle_path_siblings: [Field; 8] = [{}];",
            sibling_strs.join(", ")
        );
        println!(
            "    let merkle_path_indices: [u8; 8] = [{}];",
            index_strs.join(", ")
        );
        println!(
            "    let expected_ownership: Field = 0x{};",
            expected_ownership.to_hex()
        );
        println!("    let nft_hash: Field = 0x{};", nft_hash.to_hex());
        println!(
            "    let expected_merkle_root: Field = 0x{};",
            expected_merkle_root.to_hex()
        );
        println!();
        println!("    main(nonce, pk_x_bytes, pk_y_bytes, signature, merkle_path_siblings, merkle_path_indices, expected_ownership, nft_hash, expected_merkle_root);");
        println!("}}");
        println!("// --- End generated Noir test ---");
    }

    // -- Tests for split_proof() --

    #[test]
    fn test_split_proof_with_multiple_public_inputs() {
        let mut proof = vec![];
        proof.extend_from_slice(&2u32.to_be_bytes()); // 2 public inputs
        proof.extend_from_slice(&[1u8; 32]); // pub_input_0
        proof.extend_from_slice(&[2u8; 32]); // pub_input_1
        proof.extend_from_slice(&[3u8; 100]); // proof bytes

        let (public_inputs, proof_bytes) = split_proof(&proof).unwrap();

        assert_eq!(public_inputs.len(), 2);
        assert_eq!(public_inputs[0], vec![1u8; 32]);
        assert_eq!(public_inputs[1], vec![2u8; 32]);
        assert_eq!(proof_bytes, vec![3u8; 100]);
    }

    #[test]
    fn test_split_proof_with_single_public_input() {
        let mut proof = vec![];
        proof.extend_from_slice(&1u32.to_be_bytes()); // 1 public input
        proof.extend_from_slice(&[4u8; 32]); // pub_input_0
        proof.extend_from_slice(&[5u8; 50]); // proof bytes

        let (public_inputs, proof_bytes) = split_proof(&proof).unwrap();

        assert_eq!(public_inputs.len(), 1);
        assert_eq!(public_inputs[0], vec![4u8; 32]);
        assert_eq!(proof_bytes, vec![5u8; 50]);
    }

    #[test]
    fn test_split_proof_with_no_public_inputs() {
        let mut proof = vec![];
        proof.extend_from_slice(&0u32.to_be_bytes()); // 0 public inputs
        proof.extend_from_slice(&[6u8; 200]); // proof bytes only

        let (public_inputs, proof_bytes) = split_proof(&proof).unwrap();

        assert_eq!(public_inputs.len(), 0);
        assert_eq!(proof_bytes, vec![6u8; 200]);
    }

    #[test]
    fn test_split_proof_too_short_no_prefix() {
        let proof = vec![1u8, 2u8, 3u8]; // Only 3 bytes, need 4+ for count

        let result = split_proof(&proof);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("proof too short"));
    }

    #[test]
    fn test_split_proof_incomplete_public_inputs() {
        let mut proof = vec![];
        proof.extend_from_slice(&2u32.to_be_bytes()); // Claims 2 public inputs
        proof.extend_from_slice(&[1u8; 32]); // Only 1 public input provided
                                             // Missing second public input

        let result = split_proof(&proof);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("invalid proof format"));
    }

    // -- Integration tests (with actual circuits) --

    #[test]
    fn test_full_proof_round_trip() {
        let (nft, secret_key, nonce, merkle_path) = make_test_nft();

        let witness =
            testing::build_full_proof_witness(&nft, &secret_key, nonce, &merkle_path).unwrap();

        let circuit_bytecode = circuit_loader::load_circuit("data/full_proof.json").unwrap();
        let circuit_config = NoirCircuitConfig {
            circuit: circuit_bytecode,
            version: "0.0.1",
            low_memory: false,
            scheme: ZKMode::UltraHonkKeccak,
        };

        let circuit = NoirFullProofCircuit::setup(circuit_config).unwrap();
        let result = circuit.prove(witness.clone());

        if let Err(ref e) = result {
            eprintln!("Prove failed: {e}");
            eprintln!("Dumping witness as Noir test for debugging with `nargo test`:");
            dump_witness_for_noir_tests(&witness);
        }

        let proof = result.unwrap();
        let valid = circuit.verify(proof).unwrap();
        assert!(valid, "Full proof verification failed");
    }

    #[test]
    fn test_ownership_proof_round_trip() {
        let (nft, secret_key, nonce, _merkle_path) = make_test_nft();

        let witness = testing::build_ownership_witness(&nft, &secret_key, nonce).unwrap();

        let circuit_bytecode = circuit_loader::load_circuit("data/ownership_proof.json").unwrap();
        let circuit_config = NoirCircuitConfig {
            circuit: circuit_bytecode,
            version: "0.0.1",
            low_memory: false,
            scheme: ZKMode::UltraHonkKeccak,
        };

        let circuit = NoirOwnershipCircuit::setup(circuit_config).unwrap();
        let proof = circuit.prove(witness).unwrap();
        let valid = circuit.verify(proof).unwrap();
        assert!(valid, "Ownership proof verification failed");
    }

    // -- circuit_loader error path tests --

    #[test]
    fn test_load_circuit_from_str_invalid_json() {
        let result = circuit_loader::load_circuit_from_str("not json");
        assert!(result.is_err());
        let msg = result.unwrap_err().to_string();
        assert!(
            msg.contains("Invalid JSON"),
            "Expected 'Invalid JSON', got: {msg}"
        );
    }

    #[test]
    fn test_load_circuit_from_str_missing_bytecode() {
        let json = r#"{"hash": "abc123"}"#;
        let result = circuit_loader::load_circuit_from_str(json);
        assert!(result.is_err());
        let msg = result.unwrap_err().to_string();
        assert!(
            msg.contains("Missing 'bytecode'"),
            "Expected missing bytecode error, got: {msg}"
        );
    }

    #[test]
    fn test_load_circuit_from_str_missing_hash() {
        let json = r#"{"bytecode": "AABBCC"}"#;
        let result = circuit_loader::load_circuit_from_str(json);
        assert!(result.is_err());
        let msg = result.unwrap_err().to_string();
        assert!(
            msg.contains("Missing 'hash'"),
            "Expected missing hash error, got: {msg}"
        );
    }

    #[test]
    fn test_load_circuit_from_str_valid() {
        let json = r#"{"bytecode": "AABBCC", "hash": "abc123"}"#;
        let result = circuit_loader::load_circuit_from_str(json);
        assert!(result.is_ok());
        let circuit = result.unwrap();
        assert_eq!(circuit.bytecode, "AABBCC");
        assert_eq!(circuit.hash, "abc123");
    }

    #[test]
    fn test_load_circuit_nonexistent_file() {
        let result = circuit_loader::load_circuit("/nonexistent/path.json");
        assert!(result.is_err());
    }
}
